<?xml version="1.0" standalone="no"?>
<!DOCTYPE RESUME [
<!ELEMENT RESUME (PERSONALINFO,QUALIFICATION?,WORKEXP,EDUCATIONACHIEVEMENT,VALID)>
<!ELEMENT PERSONALINFO (NAME,ADDRESS,CONTACT)>
<!ATTLIST CONTACT Type CDATA "mobile">
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT ADDRESS (#PCDATA)>
<!ELEMENT CONTACT (#PCDATA)>
<!ELEMENT QUALIFICATION (SCHOOL+)>
<!ELEMENT SCHOOL (SCHNAME,DEGREE,GPA)>
<!ELEMENT SCHNAME (#PCDATA)>
<!ELEMENT DEGREE (#PCDATA)>
<!ELEMENT GPA (#PCDATA)>
<!ELEMENT WORKEXP (COMPANY+)>
<!ELEMENT COMPANY (COMPNAME,TITLE)>
<!ATTLIST COMPNAME Location CDATA "US">
<!ELEMENT COMPNAME (#PCDATA)>
<!ELEMENT TITLE (#PCDATA)>
<!ELEMENT EDUCATIONACHIEVEMENT (AWARD+)>
<!ELEMENT AWARD (#PCDATA)>
<!ELEMENT VALID (#PCDATA)>
<!ENTITY validurl "xmllint --valid --noout resume.xml">
]>

<RESUME>
	<PERSONALINFO>
		<NAME>S.MARIA PRIYANKA</NAME>
		<ADDRESS>4801 WESTLAND BLVD</ADDRESS>
		<CONTACT Type="personal">216 571 8116</CONTACT>
	</PERSONALINFO>
	<QUALIFICATION>
		<SCHOOL>
			<SCHNAME>TOCE UNIVERSITY</SCHNAME>
			<DEGREE>Bachelors Of Engineering</DEGREE>
			<GPA>3.5</GPA>
		</SCHOOL>
		<SCHOOL>
			<SCHNAME>UMBC</SCHNAME>
			<DEGREE>Masters in Information System</DEGREE>
			<GPA>3.0</GPA>
		</SCHOOL>
	</QUALIFICATION>
	<WORKEXP>
		<COMPANY>
			<COMPNAME Location="Bangalore">Winsys Consultancy Services</COMPNAME>
			<TITLE>Project Lead</TITLE>
		</COMPANY>
		<COMPANY>
			<COMPNAME Location="Baltimore">UMBC</COMPNAME>
			<TITLE>Technical Assitant</TITLE>
		</COMPANY>
		<COMPANY>
			<COMPNAME Location="Seattle">Microsoft</COMPNAME>
			<TITLE>C.I.O</TITLE>
		</COMPANY>
	</WORKEXP>
	<EDUCATIONACHIEVEMENT>
		<AWARD>Published IEEE paper on GESTURE INTERACTIONS</AWARD>
	</EDUCATIONACHIEVEMENT>
	<VALID>&validurl;</VALID>
</RESUME>



